title: Olivia Prior
description: Just sharing.
baseurl: "" 
url: "https://theanega.github.io"
theme: minima

# Build settings
future: true
markdown: kramdown
kramdown:
  input: GFM

nav:
  - title: Research
    url: /research/
  - title: Notes
    url: /notes/
  - title: CV  # New entry
    url: {{ site.resume }} # New entry



# Social links
social:
  github: https://github.com/theanega
  linkedin: https://linkedin.com/in/oliviaprior
  twitter: https://twitter.com/theanega
  youtube: https://youtube.com/@camilasiesta

# Resume links
resume: /assets/files/resume.pdf

# Archives
tag_archive:
  type: liquid
  permalink: /tags/

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: "default"

  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: "note"

# Add tag support
tag_page_layout: tag_page
tag_page_dir: tags

include:
  - _pages
  - _research
  - _tags
  - assets
