# Site settings
title: Olivia Prior
baseurl: ""
#url: "localhost:4000"
url: "https://theanega.github.io"
twitter_username: theanega
github_username:  theanega

# Build settings
theme: minimal
plugins:
  - jekyll-feed
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
